# Generated by Django 5.2.4 on 2025-07-15 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=6)),
                ('nama_en', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'hari',
            },
        ),
        migrations.CreateModel(
            name='MahasiswaDinus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim_dinus', models.CharField(max_length=50, unique=True)),
                ('ta_masuk', models.IntegerField(blank=True, null=True)),
                ('prodi', models.CharField(blank=True, max_length=5, null=True)),
                ('pass_mhs', models.CharField(blank=True, max_length=128, null=True)),
                ('kelas', models.IntegerField()),
                ('akdm_stat', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'mahasiswa_dinus',
            },
        ),
        migrations.CreateModel(
            name='MatkulKurikulum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kur_id', models.IntegerField()),
                ('kdmk', models.CharField(max_length=255)),
                ('nmmk', models.CharField(max_length=255)),
                ('nmen', models.CharField(blank=True, max_length=255, null=True)),
                ('tp', models.CharField(choices=[('T', 'Teori'), ('P', 'Praktik'), ('TP', 'Teori dan Praktik')], max_length=2)),
                ('sks', models.IntegerField()),
                ('sks_t', models.SmallIntegerField()),
                ('sks_p', models.SmallIntegerField()),
                ('smt', models.IntegerField()),
                ('jns_smt', models.IntegerField()),
                ('aktif', models.BooleanField()),
                ('kur_nama', models.CharField(blank=True, max_length=255, null=True)),
                ('kelompok_makul', models.CharField(choices=[('MPK', 'MPK'), ('MKK', 'MKK'), ('MKB', 'MKB'), ('MKD', 'MKD'), ('MBB', 'MBB'), ('MPB', 'MPB')], max_length=3)),
                ('kur_aktif', models.BooleanField()),
                ('jenis_matkul', models.CharField(choices=[('wajib', 'Wajib'), ('pilihan', 'Pilihan')], max_length=7)),
            ],
            options={
                'db_table': 'matkul_kurikulum',
            },
        ),
        migrations.CreateModel(
            name='SesiKuliah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jam', models.CharField(max_length=11)),
                ('sks', models.SmallIntegerField()),
                ('jam_mulai', models.TimeField(blank=True, null=True)),
                ('jam_selesai', models.TimeField(blank=True, null=True)),
                ('status', models.IntegerField()),
            ],
            options={
                'db_table': 'sesi_kuliah',
            },
        ),
        migrations.CreateModel(
            name='TahunAjaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.IntegerField(unique=True)),
                ('nama', models.CharField(max_length=50)),
                ('aktif', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tahun_ajaran',
            },
        ),
        migrations.CreateModel(
            name='JadwalTawar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta', models.IntegerField()),
                ('klpk', models.CharField(max_length=15)),
                ('klpk_2', models.CharField(blank=True, max_length=15, null=True)),
                ('kdds', models.IntegerField()),
                ('kdds2', models.IntegerField(blank=True, null=True)),
                ('jmax', models.IntegerField(default=0)),
                ('jsisa', models.IntegerField(default=0)),
                ('id_ruang1', models.IntegerField()),
                ('id_ruang2', models.IntegerField()),
                ('id_ruang3', models.IntegerField()),
                ('jns_jam', models.IntegerField()),
                ('open_class', models.BooleanField(default=True)),
                ('id_hari1', models.ForeignKey(db_column='id_hari1', on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_hari1', to='app.hari')),
                ('id_hari2', models.ForeignKey(db_column='id_hari2', on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_hari2', to='app.hari')),
                ('id_hari3', models.ForeignKey(db_column='id_hari3', on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_hari3', to='app.hari')),
                ('kdmk', models.ForeignKey(db_column='kdmk', on_delete=django.db.models.deletion.CASCADE, to='app.matkulkurikulum')),
                ('id_sesi1', models.ForeignKey(db_column='id_sesi1', on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi1', to='app.sesikuliah')),
                ('id_sesi2', models.ForeignKey(db_column='id_sesi2', on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi2', to='app.sesikuliah')),
                ('id_sesi3', models.ForeignKey(db_column='id_sesi3', on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi3', to='app.sesikuliah')),
            ],
            options={
                'db_table': 'jadwal_tawar',
            },
        ),
        migrations.CreateModel(
            name='krs_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jns_jam', models.IntegerField()),
                ('id_ruang1', models.IntegerField()),
                ('id_hari1', models.ForeignKey(db_column='id_hari1', on_delete=django.db.models.deletion.CASCADE, related_name='krs_hari1', to='app.hari')),
                ('nim_dinus', models.ForeignKey(db_column='nim_dinus', on_delete=django.db.models.deletion.CASCADE, to='app.mahasiswadinus')),
                ('kdmk', models.ForeignKey(db_column='kdmk', on_delete=django.db.models.deletion.CASCADE, to='app.matkulkurikulum')),
                ('id_sesi1', models.ForeignKey(db_column='id_sesi1', on_delete=django.db.models.deletion.CASCADE, related_name='krs_sesi1', to='app.sesikuliah')),
                ('ta', models.ForeignKey(db_column='ta', on_delete=django.db.models.deletion.CASCADE, to='app.tahunajaran')),
            ],
            options={
                'db_table': 'krs_record',
            },
        ),
    ]
