# Generated by Django 5.2.4 on 2025-07-15 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krs_record',
            name='jns_jam',
        ),
    ]
