# Generated by Django 5.2.4 on 2025-07-15 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_krs_record_jns_jam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='krs_record',
            name='id_hari1',
        ),
        migrations.RemoveField(
            model_name='krs_record',
            name='id_ruang1',
        ),
        migrations.RemoveField(
            model_name='krs_record',
            name='id_sesi1',
        ),
        migrations.AddField(
            model_name='krs_record',
            name='id_jadwal',
            field=models.ForeignKey(db_column='id_jadwal', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jadwaltawar'),
        ),
        migrations.AddField(
            model_name='krs_record',
            name='modul',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='krs_record',
            name='sks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='krs_record',
            name='sts',
            field=models.CharField(choices=[('A', 'Aktif'), ('T', 'Tidak Aktif')], max_length=1, null=True),
        ),
    ]
