# Generated by Django 5.2.4 on 2025-07-15 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_krs_record_id_hari1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs_record',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
