# Generated by Django 5.2.4 on 2025-07-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_krs_record_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswadinus',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
