# Generated by Django 5.2.4 on 2025-07-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_mahasiswadinus_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswadinus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
