# Generated by Django 5.2.4 on 2025-07-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_mahasiswadinus_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahasiswadinus',
            name='id',
        ),
        migrations.AlterField(
            model_name='mahasiswadinus',
            name='nim_dinus',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
