# Generated by Django 5.2.4 on 2025-07-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_mahasiswadinus_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahasiswadinus',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mahasiswadinus',
            name='nim_dinus',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
