# Generated by Django 5.2.4 on 2025-07-15 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_mahasiswadinus_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwaltawar',
            name='id_hari1',
        ),
        migrations.RemoveField(
            model_name='jadwaltawar',
            name='id_hari3',
        ),
        migrations.RemoveField(
            model_name='jadwaltawar',
            name='id_hari2',
        ),
        migrations.RemoveField(
            model_name='jadwaltawar',
            name='id_sesi1',
        ),
        migrations.RemoveField(
            model_name='jadwaltawar',
            name='id_sesi2',
        ),
        migrations.RemoveField(
            model_name='jadwaltawar',
            name='id_sesi3',
        ),
        migrations.RemoveField(
            model_name='jadwaltawar',
            name='kdmk',
        ),
        migrations.RemoveField(
            model_name='krs_record',
            name='id_jadwal',
        ),
        migrations.RemoveField(
            model_name='krs_record',
            name='kdmk',
        ),
        migrations.RemoveField(
            model_name='krs_record',
            name='nim_dinus',
        ),
        migrations.RemoveField(
            model_name='krs_record',
            name='ta',
        ),
        migrations.DeleteModel(
            name='Hari',
        ),
        migrations.DeleteModel(
            name='SesiKuliah',
        ),
        migrations.DeleteModel(
            name='JadwalTawar',
        ),
        migrations.DeleteModel(
            name='MatkulKurikulum',
        ),
        migrations.DeleteModel(
            name='MahasiswaDinus',
        ),
        migrations.DeleteModel(
            name='krs_record',
        ),
        migrations.DeleteModel(
            name='TahunAjaran',
        ),
    ]
