# Generated by Django 5.2.4 on 2025-07-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matkulkurikulum',
            name='id',
        ),
        migrations.AlterField(
            model_name='matkulkurikulum',
            name='kdmk',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
