# Generated by Django 5.2.4 on 2025-07-15 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_matkulkurikulum_id_alter_matkulkurikulum_kdmk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_hari1',
            field=models.ForeignKey(blank=True, db_column='id_hari1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_hari1', to='app.hari'),
        ),
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_hari2',
            field=models.ForeignKey(blank=True, db_column='id_hari2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_hari2', to='app.hari'),
        ),
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_hari3',
            field=models.ForeignKey(blank=True, db_column='id_hari3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_hari3', to='app.hari'),
        ),
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_sesi1',
            field=models.ForeignKey(blank=True, db_column='id_sesi1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi1', to='app.sesikuliah'),
        ),
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_sesi2',
            field=models.ForeignKey(blank=True, db_column='id_sesi2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi2', to='app.sesikuliah'),
        ),
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_sesi3',
            field=models.ForeignKey(blank=True, db_column='id_sesi3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi3', to='app.sesikuliah'),
        ),
    ]
