# Generated by Django 5.2.4 on 2025-07-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_jadwaltawar_id_hari1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_sesi1',
            field=models.ForeignKey(blank=True, db_column='id_sesi1', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi1', to='app.sesikuliah'),
        ),
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_sesi2',
            field=models.ForeignKey(blank=True, db_column='id_sesi2', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi2', to='app.sesikuliah'),
        ),
        migrations.AlterField(
            model_name='jadwaltawar',
            name='id_sesi3',
            field=models.ForeignKey(blank=True, db_column='id_sesi3', default=0, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jadwal_sesi3', to='app.sesikuliah'),
        ),
    ]
