# Generated by Django 5.2.4 on 2025-07-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_jadwaltawar_id_sesi1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tahunajaran',
            name='aktif',
        ),
        migrations.RemoveField(
            model_name='tahunajaran',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='tahunajaran',
            name='ta',
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='added_host',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='added_id',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='added_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='buku_tagih_jenis',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SPP'), (2, 'SKS'), (3, 'Kekurangan')], default=0),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='jns_smt',
            field=models.IntegerField(blank=True, choices=[(1, 'Reguler Ganjil'), (2, 'Reguler Genap'), (3, 'SP Ganjil'), (4, 'SP Genap')], null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='kode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='set_aktif',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='tahun_akhir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='tahun_awal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='tgl_masuk',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='update_host',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='update_id',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name='tahunajaran',
            name='update_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tahunajaran',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
