# Generated by Django 5.2.4 on 2025-07-15 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_tahunajaran_aktif_remove_tahunajaran_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwaltawar',
            name='ta',
            field=models.ForeignKey(db_column='ta', on_delete=django.db.models.deletion.CASCADE, to='app.tahunajaran'),
        ),
    ]
