# Generated by Django 5.2.4 on 2025-07-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_jadwaltawar_ta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tahunajaran',
            name='id',
        ),
        migrations.AlterField(
            model_name='tahunajaran',
            name='kode',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
