# Generated by Django 5.2.4 on 2025-07-15 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_tahunajaran_id_alter_tahunajaran_kode'),
    ]

    operations = [
        migrations.AddField(
            model_name='tahunajaran',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jadwaltawar',
            name='ta',
            field=models.ForeignKey(db_column='ta', on_delete=django.db.models.deletion.CASCADE, to='app.tahunajaran', to_field='kode'),
        ),
        migrations.AlterField(
            model_name='tahunajaran',
            name='kode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
