# Generated by Django 5.2.4 on 2025-07-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_tahunajaran_id_alter_jadwaltawar_ta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tahunajaran',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
