# Generated by Django 5.2.4 on 2025-07-16 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_tahunajaran_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='krs_record',
        ),
    ]
