# Generated by Django 5.2.4 on 2025-07-16 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_krs_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='krs_record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sts', models.CharField(choices=[('A', 'Aktif'), ('T', 'Tidak Aktif')], max_length=1, null=True)),
                ('sks', models.IntegerField(blank=True, null=True)),
                ('modul', models.IntegerField(blank=True, null=True)),
                ('id_jadwal', models.ForeignKey(db_column='id_jadwal', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.jadwaltawar')),
                ('kdmk', models.ForeignKey(db_column='kdmk', on_delete=django.db.models.deletion.CASCADE, to='app.matkulkurikulum')),
                ('nim_dinus', models.ForeignKey(db_column='nim_dinus', on_delete=django.db.models.deletion.CASCADE, to='app.mahasiswadinus')),
                ('ta', models.ForeignKey(db_column='ta', on_delete=django.db.models.deletion.CASCADE, to='app.tahunajaran')),
            ],
            options={
                'db_table': 'krs_record',
            },
        ),
    ]
