# Generated by Django 5.2.4 on 2025-07-16 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_krs_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs_record',
            name='kdmk',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
