# Generated by Django 5.2.4 on 2025-07-16 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_krs_record_kdmk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='krs_record',
            name='kdmk',
            field=models.ForeignKey(db_column='kdmk', on_delete=django.db.models.deletion.CASCADE, to='app.matkulkurikulum'),
        ),
    ]
