# Generated by Django 5.2.4 on 2025-07-16 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_krs_record_kdmk'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesiKuliahBentrok',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sesi_bentrok', models.ForeignKey(db_column='id_bentrok', on_delete=django.db.models.deletion.CASCADE, related_name='bentrok', to='app.sesikuliah')),
                ('sesi_bentrok_dengan', models.ForeignKey(db_column='id_bentrok_dengan', on_delete=django.db.models.deletion.CASCADE, related_name='bentrok_with', to='app.sesikuliah')),
            ],
            options={
                'db_table': 'sesi_kuliah_bentrok',
            },
        ),
    ]
