# Generated by Django 5.2.4 on 2025-07-16 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_sesikuliahbentrok'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='krs_record',
            new_name='KrsRecord',
        ),
        migrations.CreateModel(
            name='DaftarNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nl', models.CharField(blank=True, max_length=2, null=True)),
                ('hide', models.BooleanField(default=False)),
                ('kdmk', models.ForeignKey(db_column='kdmk', on_delete=django.db.models.deletion.CASCADE, to='app.matkulkurikulum')),
                ('nim_dinus', models.ForeignKey(db_column='nim_dinus', on_delete=django.db.models.deletion.CASCADE, to='app.mahasiswadinus')),
            ],
            options={
                'db_table': 'daftar_nilai',
            },
        ),
    ]
